basicMVO/src/models/portfolios/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template

from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
from src.common.database import Database
from src.models.portfolios.portfolio import Portfolio
from src.models.portfolios.constants import TICKERS as PortTickers
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from io import BytesIO
import urllib
import base64
import numpy as np
import math
import datetime
from src.models.stocks.stock import Stock
portfolio_blueprint = Blueprint('portfolios', __name__)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>')
@user_decorators.requires_login
def get_portfolio_page(portfolio_id):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)
    port.cal_actual_rets()
    weights = port.weights
    print(weights[0:6])
    account_balance_all = port.account_balance
    print(account_balance_all)
    rets = port.rets
    print(rets)
    n_weights = len(weights)
    n_tickers = len(PortTickers)
    start_ls = np.arange(0,n_weights,n_tickers)


    years = int(port.years)

    start_time = datetime.datetime.strptime(port.start_time, "%Y-%m-%d")
    start_year = start_time.year
    plot_url_list = []
    year_list = [start_year+x for x in range(years)]

    #plot portfolio balance
    fig = port.plot_performance(account_balance_all)
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()
    plot_url_list.append(plot_data)
    # plot returns during these quarters
    fig_2 = port.plot_return(rets)
    canvas = FigureCanvas(fig_2)
    img = BytesIO()
    fig_2.savefig(img)
    img.seek(0)
    plot_data_2 = base64.b64encode(img.read()).decode()
    plot_url_list.append(plot_data_2)
    return render_template('/portfolios/portfolio_land_page.jinja2', portfolio = port, year_count = years, year_list = year_list, plot_url_list=plot_url_list)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>/<string:year_index>')
@user_decorators.requires_login
def get_individual_portfolio(portfolio_id, year_index):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)
    #port.run_logic()
    port.years

    weights = port.weights
    wealth_allocated = port.wealth_allocated

    start_ls = np.arange(0,len(weights),len(PortTickers)*4) #we store weights for each year
    if len(start_ls) > 1 or len(weights)>0:
    #print(weights)
    #print(start_ls)
    #print(PortTickers)
    #stock = Stock.get_by_ticker()
        year_index = int(year_index)


        plot_data_list = []
        if year_index>len(start_ls)-1:
            return render_template('/portfolios/future.jinja2', portfolio=port)
        i = start_ls[year_index]
        end = i + len(PortTickers) * 4
        weights_i = weights[i:end]


        start_i = np.arange(0, len(weights_i), len(PortTickers))
        print(weights_i, start_i)


        while i < end:
            weights_each = weights[i:i+len(PortTickers)]
            wealth_each= wealth_allocated[i:i + len(PortTickers)]
            print(wealth_each)
            if len(wealth_each) == 0:
                print("hi")
                return render_template('/portfolios/portfolio.jinja2', portfolio=port, plot_url_list=plot_data_list, weights=weights_i, start_ls=start_i, year_index=year_index)

            quarter_index = int(i/len(PortTickers))
            fig = port.plot_portfolio(wealth_each, quarter_index)
            canvas = FigureCanvas(fig)
            img = BytesIO()
            fig.savefig(img)
            img.seek(0)
            plot_data = base64.b64encode(img.read()).decode()
            plot_data_list.append(plot_data)
            print(len(plot_data_list))

            i += len(PortTickers)


        return render_template('/portfolios/portfolio.jinja2', portfolio = port, plot_url_list=plot_data_list, weights = weights_i, start_ls = start_i, year_index = year_index)

    else:

        return render_template('/portfolios/future.jinja2', portfolio= port)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>/performance')
@user_decorators.requires_login
def get_performance_by_year(portfolio_id):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)

    achieved_rets, account_balance_all = port.cal_actual_rets()

    fig = port.plot_performance(account_balance_all)
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()
    #plot_data_list.append(plot_data)
    #i += len(PortTickers)


    return render_template('/portfolios/performance.jinja2', portfolio = port, plot_url_list=plot_data)






@portfolio_blueprint.route('/edit/<string:portfolio_id>', methods=['GET','POST'])
@user_decorators.requires_login
def update_portfolio(portfolio_id):         # Views form to change portfolio's associated risk aversion parameter
    port = Portfolio.get_by_id(portfolio_id)
    if request.method == "POST":
        #risk_appetite = request.form['risk_appetite']
        port.description = request.form['goal_description']
        port.amount = request.form['Amount_for_goal']
        port.initial_deposit = request.form['initial_deposit']
        port.years = request.form['years_to_achieve']
        port.importance = request.form['importance']
        port.start_time = request.form['start_time']
        #port.risk_appetite = risk_appetite
        port.run_logic()
        #port.save_to_mongo()


        return redirect(url_for(".get_portfolio_page", portfolio_id=port._id))

        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio = port, plot_url=plot_data)

    return render_template('/portfolios/edit_portfolio.jinja2', portfolio=port)

@portfolio_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_login
def create_portfolio():            # Views form to create portfolio associated with active/ loggedin user
    if request.method == "POST":
        desc = request.form['goal_description']
        amount = request.form['Amount_for_goal']
        goal_type = request.form['goal_type']
        initial_deposit = request.form['initial_deposit']
        years = request.form['years_to_achieve']
        importance = request.form['importance']
        start_time = request.form['start_time']
        injection = request.form["injection"]
        port = Portfolio(session['email'], desc, goal_type, amount, initial_deposit,years, importance, injection, start_time = start_time)
        user = User.find_by_email(session['email'])
        user.number_goals+=1
        user.save_to_mongo()
        #port.get_Params()
        #description, amount, initial_deposit, years, importance, risk_appetite
        port.run_logic()
        #print(port.weights)

        '''
        fig = port.runMVO()
        canvas = FigureCanvas(fig)
        img = BytesIO()
        fig.savefig(img)
        img.seek(0)
        plot_data = base64.b64encode(img.read()).decode()
        '''
        return redirect(url_for(".create_success"))
        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio=port, plot_url=plot_data)

    return render_template('/portfolios/new_portfolio.jinja2')

@portfolio_blueprint.route('/create_success')
@user_decorators.requires_login
def create_success():            # Views form to create portfolio associated with active/ loggedin user

        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio=port, plot_url=plot_data)

    return render_template('/portfolios/created_successful.jinja2')





@portfolio_blueprint.route('/delete/<string:portfolio_id>')
@user_decorators.requires_login
def delete_portfolio(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    Database.remove("portfolios",{"_id":portfolio_id})
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()
    return render_template('/users/portfolios.jinja2', portfolios = portfolios, user=user)

@portfolio_blueprint.route('/test/<string:portfolio_id>')
@user_decorators.requires_login
def test_portfolio(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    port = Portfolio.get_by_id(portfolio_id)
    port.run_logic()

    return render_template('/portfolios/weight_table.jinja2', portfolio= port)
'''
@portfolio_blueprint.route('/test/<string:portfolio_id>')
@user_decorators.requires_login
def delete_all_portfolios(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    port = Portfolio.get_by_id(portfolio_id)
    Database.remove("portfolios", {"_id": port.user_email})
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()
    return render_template('/users/portfolios.jinja2', portfolios=portfolios)
'''

basicMVO/src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template

from src.models.users.user import User

from src.models.portfolios.portfolio import Portfolio
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
import datetime
user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods = ['GET','POST'])
def login_user():   # Views form required for user login
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                ## CHANGE ##
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")

@user_blueprint.route('/register', methods = ['GET','POST'])
def register_user():   # Views form required for user signup
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        try:
            if User.register_user(email,password, first_name, last_name):
                session['email'] = email
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")

@user_blueprint.route('/logout')
def logout_user():  # Logs user out
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/portfolios')
@user_decorators.requires_login
def user_portfolios():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()

    return render_template('/users/portfolios.jinja2', portfolios = portfolios, user = user)
@user_blueprint.route('/update_profile', methods = ['GET','POST'])
@user_decorators.requires_login
def update_profile():  # Views list of user portfolios
    if request.method == 'POST':
        age = request.form['age']
        position = request.form['position']
        current_asset = request.form['current_asset']
        current_debt = request.form['current_debt']
        user = User.find_by_email(session['email'])
        user.update_profile(age, position,float(current_asset),float(current_debt))
        return redirect(url_for(".user_profile"))

    return render_template("users/update_profile.jinja2")


@user_blueprint.route('/profile')
@user_decorators.requires_login
def user_profile():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    user.update_balance()
    ports= Portfolio.get_by_email(session['email'])
    date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return render_template('/users/profile_page.jinja2', user = user, ports=ports, current_date = date)

basicMVO/src/templates/users/login.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>
	<style>
	.form-group{
        font-family: Helvetica;

        border: none
    }

    .container{
        margin-top: 200px;
    }


	</style>
	{% include "html_dependencies.html" %}
</head>
<body style="background-color: #404040">
    <div class="container" style="background-color: #404040">
        <div class="d-flex align-items-center flex-column justify-content-center h-100 text-white" id="header">
            <h1 class="display-4">Hello.</h1>
            <form action="{{ url_for('users.login_user') }}" method="post">
                <div class="form-group" >
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name='email' placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.
                    </small>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name='password' placeholder="Password">
                </div>
                <div class="row justify-content-end" style="padding-right: 20px">
                <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>
</body>
</html>

basicMVO/src/templates/users/portfolios.jinja2
{% extends "base.jinja2" %}
{% block content %}
<head>
    <style>

    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
            <h1><br>All your goals are listed here</br></h1>
            </div>

        <p style="border-top: 1px solid"></p>
        </div>
    </div>
    {% if portfolios%}
        {% for portfolio in portfolios %}
            <a href="{{ url_for('portfolios.get_portfolio_page', portfolio_id=portfolio._id) }}" class="list-group-item list-group-item-action">
                <h4>{{ portfolio.goal_type }} </h4>
                Start Date for this goal: <strong>{{ portfolio.start_time }}</strong><br/>
            </a>
        {% endfor %}
        <a href="{{ url_for('portfolios.create_portfolio') }}" class="btn btn-primary" style="margin-top: 15px;float:right;">Create New Portfolio</a>
    {% else %}
        <div class="row" style="margin-top: 15px;float:right;">
        <a href="{{ url_for('portfolios.create_portfolio') }}" class="btn btn-primary" >Create First Goal</a>
        </div>
    {% endif %}
</body>
{% endblock %}

basicMVO/src/templates/users/profile_page.jinja2
{% extends "base.jinja2" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic MVO</title>
    <style>
    .col{
      right:0
    }
    ul{
    list-style: none;
    }

    </style>
    {% include "html_dependencies.html" %}

</head>
<body>
<div class="container">
    <div class="row justify-content-start" style="margin-top: 50px">
        <div class="col-4">
            <h1>{{user.first_name}}'s Account</h1>

        </div>
        <div class="col align-self-center">

            <a class="btn btn-primary" href = "{{url_for('users.update_profile')}}">Update your account<a>
        </div>


    </div>

    <div class="row align-items-top">
        <div class="col">
            <div class="row">
                <img src="/static/css/profile.png">
            </div>
            <div class="row">
                <ul>
                     <li>Your age: {{user.age}}</li>
                     <li>Your current position: {{user.position}} </li>

                     <li>Number of goals: {{user.number_goals}}</li>

                </ul>
            </div>
        </div>
        <div class="col-8">
            <div class="row">
            <h2 style="margin-top:20px;margin-left: 10px;">Total Account Balance in Goals: </h2><br>
            </div>
            <div class="row">
            <p style="margin-left: 10px; font-size:40px;">${{user.total_balance|round(2)}}</p>
            </div>
            <div class="row justify-content-start">
            <div class="col-6">
            <h1 style="margin-left: 3px; font-size:30px;">Current Asset: ${{user.current_asset|round(2)}}</h1><br>
            </div>
            <div class="col-5">
            <h1 style="margin-left: 3px;font-size:30px;color: red;">Current Debt: ${{user.current_debt|round(2)}}</h1><br>
            </div>
            </div>


            <div class="row">
                <table class="table" id="t_1">
                    <thead>
                        <tr>
                            <th>Type of Goal</th>

                            <th>Current time</th>
                            <th>Start Date</th>

                            <th>Terminal Date</th>
                            <th>Initial Deposit</th>
                            <th>Target Amount</th>
                            <th>Last Account Balance</th>

                            <th>Estimated Monthly Deposit</th>
                        </tr>
                    </thead>
                    <tbody>

                            {% for i in ports %}
                            <tr>
                                <td>{{i.goal_type}}</td>
                                <td>{{current_date}}</td>
                                <td>{{i.start_time}}</td>
                                <td>{{i.terminal_date}}</td>

                                <td>${{i.initial_deposit}}</td>
                                <td>${{i.amount}}</td>
                                <td>${{i.account_balance[-1]|round(2)}}</td>
                                <td>${{i.injection}}</td>
                            </tr>
                            {% endfor %}

                    </tbody>
                 </table>
            </div>
        </div>

    </div>



</div>
</body>
</html>
{% endblock %}

basicMVO/src/templates/users/register.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>
	<style>
	.form-group{
        font-family: Helvetica;
        border: none
    }

    .container{
        margin-top: 200px;
    }


	</style>
	{% include "html_dependencies.html" %}
</head>
<body style="background-color: #404040">
    <div class="container" style="background-color: #404040">
        <div class="d-flex align-items-center flex-column justify-content-center h-100 text-white" id="header">
            <h1 class="display-4">Let's start the journey!</h1>
            <form action="{{ url_for('users.register_user') }}" method="post">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name='email' placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name='password' placeholder="Password">
                </div>

                <div class="form-group">
                    <label for="first_name">What is your first name?</label>
                    <input type="text" class="form-control" placeholder="Jenny" id="first_name" name="first_name">
                </div>

                <div class="form-group">
                    <label for="last_name">What is your last name?</label>
                    <input type="text" class="form-control" placeholder="Doe" id="last_name" name="last_name">
                </div>



                <button type="submit" class="btn btn-primary" style="float:right;">Sign up</button>
            </form>
        </div>
    </div>
</body>
</html>

basicMVO/src/templates/users/update_profile.jinja2
{% extends "base.jinja2" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>
	<style>
	.h1{
	    color: white
	}
    .form-group{

        font-family: Helvetica;
        background-color:transparent;
        font-size: 20px;
    }
    .col{
        margin-top: 50px
    }
    </style>
	{% include "html_dependencies.html" %}
</head>
<body>
    <div class="col">
    <div class="form-size" style="background-color:transparent; border:none;">
        <form action="{{ url_for('users.update_profile') }}" method="post">
            <h1 style="font-style: italic">Hi, there!</h1>
            <div class="form-group">
                <label for="age">How old are you?</label>
                <input type="number" class="form-control" id="age" name='age' placeholder="34">
            </div>
            <div class="form-group">
                <label for="position">What is your current job position?</label>
                <input type="text" class="form-control" id="position" name='position' placeholder="Ex: Doctor, Student">
            </div>

            <div class="form-group">
                <label for="current_asset">What is the current amount of money in your asset account? To clarify, could you please estimate the amount of money you have in your bank account?</label>
                <input type="number" class="form-control" placeholder="10000" id="current_asset" name="current_asset">
            </div>

            <div class="form-group">
                <label for="current_debt">What is the current amount of money in your debt account?</label>
                <input type="number" class="form-control" placeholder="5000" id="current_debt" name="current_debt">
            </div>


            <div class="row">
            <div class="col">
            <button type="submit" class="btn btn-primary" style="float: right">Submit</button>
            </div>
            <div class="col align-self-center">

            <a href="{{ url_for('users.user_profile') }}">Return to Your Profile Page</a>
            </div>
            </div>
        </form>
    </div>
    </div>
</body>
</html>
{% endblock %}