basicMVO/src/models/stocks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, json

from src.common.database import Database
from src.models.stocks.stock import Stock
import src.models.users.decorators as user_decorators
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from io import BytesIO
import base64
import pandas

stock_blueprint = Blueprint('stocks', __name__)

@stock_blueprint.route('/')
def index():    # Views list of available/stored stocks
    stocks = Stock.all()
    return render_template('stocks/stock_index.jinja2', stocks = stocks)

'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock = stock)
'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique portfolio page
    stock = Stock.get_by_ticker(stock_ticker)
    prices = pandas.read_json(stock.prices)
    rets = pandas.read_json(stock.returns)
    print(prices)
    print(rets)
    fig = stock.plot_stock()
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()

    return render_template('stocks/stock.jinja2', stock = stock, plot_url=plot_data)
'''
@stock_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_admin_permissions
def create_stock(): 

    if request.method == 'POST':
        pass

    return render_template('stocks/new_stock.jinja2')


@stock_blueprint.route('/delete/<string:stock_id>', methods=['GET'])
@user_decorators.requires_admin_permissions
def delete_stock(stock_id):
    Stock.get_by_ticker(stock_id).remove()

    return redirect(url_for('.index'))

'''

basicMVO/src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template

from src.models.users.user import User

from src.models.portfolios.portfolio import Portfolio
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
import datetime
user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods = ['GET','POST'])
def login_user():   # Views form required for user login
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                ## CHANGE ##
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")

@user_blueprint.route('/register', methods = ['GET','POST'])
def register_user():   # Views form required for user signup
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        try:
            if User.register_user(email,password, first_name, last_name):
                session['email'] = email
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")

@user_blueprint.route('/logout')
def logout_user():  # Logs user out
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/portfolios')
@user_decorators.requires_login
def user_portfolios():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()

    return render_template('/users/portfolios.jinja2', portfolios = portfolios, user = user)
@user_blueprint.route('/update_profile', methods = ['GET','POST'])
@user_decorators.requires_login
def update_profile():  # Views list of user portfolios
    if request.method == 'POST':
        age = request.form['age']
        position = request.form['position']
        current_asset = request.form['current_asset']
        current_debt = request.form['current_debt']
        user = User.find_by_email(session['email'])
        user.update_profile(age, position,float(current_asset),float(current_debt))
        return redirect(url_for(".user_profile"))

    return render_template("users/update_profile.jinja2")


@user_blueprint.route('/profile')
@user_decorators.requires_login
def user_profile():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    user.update_balance()
    ports= Portfolio.get_by_email(session['email'])
    date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return render_template('/users/profile_page.jinja2', user = user, ports=ports, current_date = date)

basicMVO/src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic MVO</title>
    <style>
    .navbar-inverse {

     background-color: #222;
     border-color: #080808;
    }
    .nav-link{
    color: lightgray;
    font-size:20px
    }
    body{
        background-image: url("/static/css/bg.png");



    }
    </style>
    {% include "html_dependencies.html" %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-inverse" style="height:70px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar_right" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
        <div class="collapse navbar-collapse" id="navbar">
            <a class="navbar-brand" href="#" title="Home">Smart Invest</a>
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_portfolios') }}">Goals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('stocks.index') }}">Assets</a>
                </li>

            </ul>
        </div>
      {% if session['email'] %}
          <div class="collapse navbar-collapse justify-content-end" id="navbar">

               <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('stocks.index') }}">About Us</a>
                </li>
              <a class="btn btn-primary" href="{{ url_for('users.logout_user') }}" role="button">Log Out</a>
          </div>
      {% else %}
          <div class="collapse navbar-collapse justify-content-end" id="navbar">
              <a class="btn btn-primary" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
              <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.login_user') }}">Login</a>
                </li>
              </ul>
          </div>
      {% endif %}
    </div>
</nav>

<div class="content container">
    {% block content %}

    {% endblock%}
</div>

</body>
</html>

basicMVO/src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">SmartInvest</h1>
        <br>
        <p> Do you want to get rid of the pain of figuring out best way to invest your money? Join us today to
            get smart financing advices from our automated financial advisor!
            </p>
        <p>Just sign up, set your risk appetite, and we'll do the rest!</p>
        {% if session['email'] %}
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{{ url_for('users.logout_user') }}" role="button">Log Out</a>
            </p>
        {% else %}
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a>
            </p>
        {% endif %}
    </div>
{% endblock %}

basicMVO/src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}"/>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

basicMVO/src/templates/index.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>

	<link rel="stylesheet" href="{{ url_for('static', filename = 'css/bulma.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/css.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'font-awesome/css/font-awesome.min.css') }}">
</head>
<body>
	<div class="topNav">
		<div class="logo">
			Smart Invest
		</div>
		<div class="buttons">
			<a href="" class="button is-white">
				<span class="icon">
  				<i class="fa fa-envelope"></i>
				</span>
			</a>
			<a href="" class="button is-white">
				<span class="icon">
  				<i class="fa fa-bell"></i>
				</span>
			</a>
			<a href="" class="button is-white">
				<span class="icon">
  				<i class="fa fa-user"></i>
				</span>
			</a>
		</div>
	</div>
	<div class="body">
		<div class="shadowLayer"></div>
		<div class="centerBox">
			<p class="title is-1 is-spaced" style="font-size: 60px;">Smart Invest</p>
			<p class="subtitle is-4 is-spaced">Invest now, harvest in future!</p>
			<hr style="height: 2px; margin-top: 10px;" />
			<div class="centerButtons">
				<a class="button" href={{ url_for('users.register_user') }}>
			    <span class="icon">
			      <i class="fa fa-pie-chart"></i>
			    </span>
			    <span>Join Us</span>
			  </a>
			  <a class="button" href="{{ url_for('users.login_user') }}">
			    <span class="icon">
			      <i class="fa fa-key"></i>
			    </span>
			    <span>Log in</span>
			  </a>
			  <!--
			 	<a class="button">
			    <span class="icon">
			      <i class="fa fa-github"></i>
			    </span>
			    <span>GitHub</span>
			  </a>
			  -->
			</div>
		</div>
	</div>
</body>
</html>