basicMVO/src/models/stocks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, json

from src.common.database import Database
from src.models.stocks.stock import Stock
import src.models.users.decorators as user_decorators
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from io import BytesIO
import base64
import pandas

stock_blueprint = Blueprint('stocks', __name__)

@stock_blueprint.route('/')
def index():    # Views list of available/stored stocks
    stocks = Stock.all()
    return render_template('stocks/stock_index.jinja2', stocks = stocks)

'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock = stock)
'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique portfolio page
    stock = Stock.get_by_ticker(stock_ticker)
    prices = pandas.read_json(stock.prices)
    rets = pandas.read_json(stock.returns)
    print(prices)
    print(rets)
    fig = stock.plot_stock()
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()

    return render_template('stocks/stock.jinja2', stock = stock, plot_url=plot_data)
'''
@stock_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_admin_permissions
def create_stock(): 

    if request.method == 'POST':
        pass

    return render_template('stocks/new_stock.jinja2')


@stock_blueprint.route('/delete/<string:stock_id>', methods=['GET'])
@user_decorators.requires_admin_permissions
def delete_stock(stock_id):
    Stock.get_by_ticker(stock_id).remove()

    return redirect(url_for('.index'))

'''

basicMVO/src/templates/stocks/new_stock.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>New page! No content yet</h1>
{% endblock %}

basicMVO/src/templates/stocks/stock.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="mt-3">
        <h1>{{ stock.ticker }} <small class="h4 text-muted">Summary</small></h1>
    </div>
    <hr>
    <div class="container">
    <div class="row">
        <!--
        <div class="col">
            <img src="https://www.google.com/finance/getchart?q={{ stock.ticker }}&p=10Y&i=86400" />
        </div>
        -->
        <div class="col-8">
                <img src="data:image/png;base64, {{ plot_url }}" width="700" height="500" alt="graph">
            </div>
        <div class="col align-self-center">
            <div class="row">
            <p>Please click on the link below to learn more about this asset! <br> <a href= {{stock.info_url}}>Yahoo Finance Page for this ETF</a></p>

            </div>
            <div class="row">
            <h5>Characteristics</h5>
            </div>
            <div class="row">
                <p>Annual Expected Return: <strong>{{ 100*stock.mu |round(3) }}%</strong></p>
            </div>
            <div class="row">
                <p>Annual Standard Deviation: <strong>{{ 100*stock.std |round(2) }}%</strong></p>
            </div>

        </div>
    </div>
    </div>
{% endblock %}

basicMVO/src/templates/stocks/stock_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="mt-3">
        <h1><br>List of available assets</br></h1>
        <p>The following ETFs are the selected assets that we use to allocate your money.</p>
    </div>
    <hr>
    <div class="list-group">
        {% for stock in stocks %}
            <a href="{{ url_for('stocks.stock_page',stock_ticker = stock.ticker) }}" class="list-group-item list-group-item-action">
                <h4>{{ stock.ticker }}</h4>
                Expected Return: <strong>{{ stock.mu |round(5) }}</strong><br/>
                Standard Deviation: <strong>{{ stock.std |round(5) }}</strong><br/>
            </a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success mt-3" href="{{ url_for('stocks.create_stock') }}" role="button">Create new</a>
    {% endif %}
{% endblock %}