basicMVO/src/models/portfolios/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template

from src.models.users.user import User
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
from src.common.database import Database
from src.models.portfolios.portfolio import Portfolio
from src.models.portfolios.constants import TICKERS as PortTickers
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from io import BytesIO
import urllib
import base64
import numpy as np
import math
import datetime
from src.models.stocks.stock import Stock
portfolio_blueprint = Blueprint('portfolios', __name__)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>')
@user_decorators.requires_login
def get_portfolio_page(portfolio_id):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)
    port.cal_actual_rets()
    weights = port.weights
    print(weights[0:6])
    account_balance_all = port.account_balance
    print(account_balance_all)
    rets = port.rets
    print(rets)
    n_weights = len(weights)
    n_tickers = len(PortTickers)
    start_ls = np.arange(0,n_weights,n_tickers)


    years = int(port.years)

    start_time = datetime.datetime.strptime(port.start_time, "%Y-%m-%d")
    start_year = start_time.year
    plot_url_list = []
    year_list = [start_year+x for x in range(years)]

    #plot portfolio balance
    fig = port.plot_performance(account_balance_all)
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()
    plot_url_list.append(plot_data)
    # plot returns during these quarters
    fig_2 = port.plot_return(rets)
    canvas = FigureCanvas(fig_2)
    img = BytesIO()
    fig_2.savefig(img)
    img.seek(0)
    plot_data_2 = base64.b64encode(img.read()).decode()
    plot_url_list.append(plot_data_2)
    return render_template('/portfolios/portfolio_land_page.jinja2', portfolio = port, year_count = years, year_list = year_list, plot_url_list=plot_url_list)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>/<string:year_index>')
@user_decorators.requires_login
def get_individual_portfolio(portfolio_id, year_index):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)
    #port.run_logic()
    port.years

    weights = port.weights
    wealth_allocated = port.wealth_allocated

    start_ls = np.arange(0,len(weights),len(PortTickers)*4) #we store weights for each year
    if len(start_ls) > 1 or len(weights)>0:
    #print(weights)
    #print(start_ls)
    #print(PortTickers)
    #stock = Stock.get_by_ticker()
        year_index = int(year_index)


        plot_data_list = []
        if year_index>len(start_ls)-1:
            return render_template('/portfolios/future.jinja2', portfolio=port)
        i = start_ls[year_index]
        end = i + len(PortTickers) * 4
        weights_i = weights[i:end]


        start_i = np.arange(0, len(weights_i), len(PortTickers))
        print(weights_i, start_i)


        while i < end:
            weights_each = weights[i:i+len(PortTickers)]
            wealth_each= wealth_allocated[i:i + len(PortTickers)]
            print(wealth_each)
            if len(wealth_each) == 0:
                print("hi")
                return render_template('/portfolios/portfolio.jinja2', portfolio=port, plot_url_list=plot_data_list, weights=weights_i, start_ls=start_i, year_index=year_index)

            quarter_index = int(i/len(PortTickers))
            fig = port.plot_portfolio(wealth_each, quarter_index)
            canvas = FigureCanvas(fig)
            img = BytesIO()
            fig.savefig(img)
            img.seek(0)
            plot_data = base64.b64encode(img.read()).decode()
            plot_data_list.append(plot_data)
            print(len(plot_data_list))

            i += len(PortTickers)


        return render_template('/portfolios/portfolio.jinja2', portfolio = port, plot_url_list=plot_data_list, weights = weights_i, start_ls = start_i, year_index = year_index)

    else:

        return render_template('/portfolios/future.jinja2', portfolio= port)

@portfolio_blueprint.route('/portfolio/<string:portfolio_id>/performance')
@user_decorators.requires_login
def get_performance_by_year(portfolio_id):   # Renders unique portfolio page
    port = Portfolio.get_by_id(portfolio_id)

    achieved_rets, account_balance_all = port.cal_actual_rets()

    fig = port.plot_performance(account_balance_all)
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()
    #plot_data_list.append(plot_data)
    #i += len(PortTickers)


    return render_template('/portfolios/performance.jinja2', portfolio = port, plot_url_list=plot_data)






@portfolio_blueprint.route('/edit/<string:portfolio_id>', methods=['GET','POST'])
@user_decorators.requires_login
def update_portfolio(portfolio_id):         # Views form to change portfolio's associated risk aversion parameter
    port = Portfolio.get_by_id(portfolio_id)
    if request.method == "POST":
        #risk_appetite = request.form['risk_appetite']
        port.description = request.form['goal_description']
        port.amount = request.form['Amount_for_goal']
        port.initial_deposit = request.form['initial_deposit']
        port.years = request.form['years_to_achieve']
        port.importance = request.form['importance']
        port.start_time = request.form['start_time']
        #port.risk_appetite = risk_appetite
        port.run_logic()
        #port.save_to_mongo()


        return redirect(url_for(".get_portfolio_page", portfolio_id=port._id))

        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio = port, plot_url=plot_data)

    return render_template('/portfolios/edit_portfolio.jinja2', portfolio=port)

@portfolio_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_login
def create_portfolio():            # Views form to create portfolio associated with active/ loggedin user
    if request.method == "POST":
        desc = request.form['goal_description']
        amount = request.form['Amount_for_goal']
        goal_type = request.form['goal_type']
        initial_deposit = request.form['initial_deposit']
        years = request.form['years_to_achieve']
        importance = request.form['importance']
        start_time = request.form['start_time']
        injection = request.form["injection"]
        port = Portfolio(session['email'], desc, goal_type, amount, initial_deposit,years, importance, injection, start_time = start_time)
        user = User.find_by_email(session['email'])
        user.number_goals+=1
        user.save_to_mongo()
        #port.get_Params()
        #description, amount, initial_deposit, years, importance, risk_appetite
        port.run_logic()
        #print(port.weights)

        '''
        fig = port.runMVO()
        canvas = FigureCanvas(fig)
        img = BytesIO()
        fig.savefig(img)
        img.seek(0)
        plot_data = base64.b64encode(img.read()).decode()
        '''
        return redirect(url_for(".create_success"))
        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio=port, plot_url=plot_data)

    return render_template('/portfolios/new_portfolio.jinja2')

@portfolio_blueprint.route('/create_success')
@user_decorators.requires_login
def create_success():            # Views form to create portfolio associated with active/ loggedin user

        #return render_template('/portfolios/optimal_portfolio.jinja2', portfolio=port, plot_url=plot_data)

    return render_template('/portfolios/created_successful.jinja2')





@portfolio_blueprint.route('/delete/<string:portfolio_id>')
@user_decorators.requires_login
def delete_portfolio(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    Database.remove("portfolios",{"_id":portfolio_id})
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()
    return render_template('/users/portfolios.jinja2', portfolios = portfolios, user=user)

@portfolio_blueprint.route('/test/<string:portfolio_id>')
@user_decorators.requires_login
def test_portfolio(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    port = Portfolio.get_by_id(portfolio_id)
    port.run_logic()

    return render_template('/portfolios/weight_table.jinja2', portfolio= port)
'''
@portfolio_blueprint.route('/test/<string:portfolio_id>')
@user_decorators.requires_login
def delete_all_portfolios(portfolio_id):            # Views form to create portfolio associated with active/ loggedin user
    port = Portfolio.get_by_id(portfolio_id)
    Database.remove("portfolios", {"_id": port.user_email})
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()
    return render_template('/users/portfolios.jinja2', portfolios=portfolios)
'''

basicMVO/src/models/stocks/views.py
from flask import Blueprint, render_template, request, redirect, url_for, json

from src.common.database import Database
from src.models.stocks.stock import Stock
import src.models.users.decorators as user_decorators
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from io import BytesIO
import base64
import pandas

stock_blueprint = Blueprint('stocks', __name__)

@stock_blueprint.route('/')
def index():    # Views list of available/stored stocks
    stocks = Stock.all()
    return render_template('stocks/stock_index.jinja2', stocks = stocks)

'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique stock page
    stock = Stock.get_by_ticker(stock_ticker)
    return render_template('stocks/stock.jinja2', stock = stock)
'''
@stock_blueprint.route('/stock/<string:stock_ticker>')
def stock_page(stock_ticker):   # Renders unique portfolio page
    stock = Stock.get_by_ticker(stock_ticker)
    prices = pandas.read_json(stock.prices)
    rets = pandas.read_json(stock.returns)
    print(prices)
    print(rets)
    fig = stock.plot_stock()
    canvas = FigureCanvas(fig)
    img = BytesIO()
    fig.savefig(img)
    img.seek(0)
    plot_data = base64.b64encode(img.read()).decode()

    return render_template('stocks/stock.jinja2', stock = stock, plot_url=plot_data)
'''
@stock_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_admin_permissions
def create_stock(): 

    if request.method == 'POST':
        pass

    return render_template('stocks/new_stock.jinja2')


@stock_blueprint.route('/delete/<string:stock_id>', methods=['GET'])
@user_decorators.requires_admin_permissions
def delete_stock(stock_id):
    Stock.get_by_ticker(stock_id).remove()

    return redirect(url_for('.index'))

'''

basicMVO/src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template

from src.models.users.user import User

from src.models.portfolios.portfolio import Portfolio
import src.models.users.errors as UserErrors
import src.models.users.decorators as user_decorators
import datetime
user_blueprint = Blueprint('users', __name__)

@user_blueprint.route('/login', methods = ['GET','POST'])
def login_user():   # Views form required for user login
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                ## CHANGE ##
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")

@user_blueprint.route('/register', methods = ['GET','POST'])
def register_user():   # Views form required for user signup
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        try:
            if User.register_user(email,password, first_name, last_name):
                session['email'] = email
                return redirect(url_for(".user_profile"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")

@user_blueprint.route('/logout')
def logout_user():  # Logs user out
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/portfolios')
@user_decorators.requires_login
def user_portfolios():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    portfolios = user.get_portfolios()

    return render_template('/users/portfolios.jinja2', portfolios = portfolios, user = user)
@user_blueprint.route('/update_profile', methods = ['GET','POST'])
@user_decorators.requires_login
def update_profile():  # Views list of user portfolios
    if request.method == 'POST':
        age = request.form['age']
        position = request.form['position']
        current_asset = request.form['current_asset']
        current_debt = request.form['current_debt']
        user = User.find_by_email(session['email'])
        user.update_profile(age, position,float(current_asset),float(current_debt))
        return redirect(url_for(".user_profile"))

    return render_template("users/update_profile.jinja2")


@user_blueprint.route('/profile')
@user_decorators.requires_login
def user_profile():  # Views list of user portfolios
    user = User.find_by_email(session['email'])
    user.update_balance()
    ports= Portfolio.get_by_email(session['email'])
    date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return render_template('/users/profile_page.jinja2', user = user, ports=ports, current_date = date)

basicMVO/src/templates/portfolios/created_successful.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>
	<style>
	.form-group{
        font-family: Helvetica;

        border: none
    }

    .container{
        margin-top: 200px;
    }


	</style>
	{% include "html_dependencies.html" %}
</head>
<body style="background-color: #404040">
    <div class="container" style="background-color: #404040">
        <div class="d-flex align-items-center flex-column justify-content-center h-100 text-white" id="header">
            <h1 class="display-4">New Goal has been created!</h1>

            <div class="row justify-content-end" style="padding-right: 20px">
                <a href="{{ url_for('users.user_portfolios') }}" class="btn btn-success" >Return to your goal page!</a>
            </div>
        </div>
    </div>
</body>
</html>

basicMVO/src/templates/portfolios/edit_portfolio.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <head>
    <style>
    .form-group{

        font-family: Helvetica;
        background-color:transparent;
        border: none;
        font-size: 20px;
    }
    .form-size{
        background-color:transparent;
        border: none;
        padding: 5px;
        font-family: Helvetica;
    }
    #form_title{
        margin-top: 30px;
    }
    </style>
    </head>
    <div class="row">
    <div class="col-8 m-4">
        <h1>Please feel free to update your goal!</h1>
    </div>
    <div class="col align-self-center">
        <a href="{{ url_for('portfolios.get_portfolio_page', portfolio_id=portfolio._id) }}">Return to Your Portfolio Summary Page</a>
    </div>
    </div>
    <hr>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                      <label for="start_time">1. Please input the start time for this portfolio:</label>
                      <textarea class="form-control" rows="1" id="start_time" name="start_time" placeholder='In the format of "2014-01-01"'></textarea>
            </div>
            <div class="form-group">
                 <label for="goal_description">2. Could you please describe your goal?</label>
                 <textarea class="form-control" id="goal_description" name="goal_description" rows="2" placeholder="Ex: I want to afford my kid's intuition fee for his university."></textarea>
            </div>

            <div class="form-group">
                <label for="goal_type">3. What type of goal is this?</label>
                    <select class="form-control" id="goal_type" name="goal_type">
                      <option>Education Fund</option>
                      <option>Housing Mortgage</option>
                      <option>Retirement Fund</option>
                      <option>Wedding Fund</option>
                      <option>Gift Fund</option>
                      <option>Other</option>
                    </select>
              </div>

            <div class="form-group">
                <label for="years_to_achieve">4. How long do you expect to achieve this goal?</label>
                    <select class="form-control" id="years_to_achieve" name="years_to_achieve">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                      <option>5</option>
                      <option>6</option>
                      <option>7</option>
                      <option>8</option>
                      <option>9</option>
                      <option>10</option>
                      <option>11</option>
                      <option>12</option>
                      <option>13</option>
                      <option>14</option>
                      <option>15</option>
                      <option>16</option>
                      <option>17</option>
                      <option>18</option>
                      <option>19</option>
                      <option>20</option>
                    </select>
              </div>




            <div class = "form-group">
                <label for="initial_deposit">5. How much money could you deposit for this goal now?</label>

                    <div class="input-group">

                      <span class="input-group-addon">$</span>
                      <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="initial_deposit" name="initial_deposit" >
                      <span class="input-group-addon">.00</span>
                    </div>
            </div>
            <div class = "form-group">
                <label for="Amount_for_goal">6. How much money do you expect to withdraw by the end date of this goal?</label>

                    <div class="input-group">

                      <span class="input-group-addon">$</span>
                      <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="Amount_for_goal" name="Amount_for_goal" >
                      <span class="input-group-addon">.00</span>
                    </div>
            </div>

            <div class = "form-group">
                <label for="injection">7. Could you deposit money to this portfolio every 3 months? If yes, could you indicate the amount of money? </label>

                    <div class="input-group">

                      <span class="input-group-addon">$</span>
                      <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" id="injection" name="injection" >
                      <span class="input-group-addon">.00</span>
                    </div>
            </div>


            <fieldset class="form-group">
                <label for="importance">8. How eager do you want to achieve your goal?</label>
                        <div class="form-check">
                          <label class="form-check-label">
                            <input type="radio" class="form-check-input" name="importance" id="optionsRadios1" value="3" checked>
                            I must achieve this goal before or by the terminal date.
                          </label>
                        </div>

                        <div class="form-check">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input" name="importance" id="optionsRadios2" value="2">
                            I hope I could achieve this goal, but I do not mind this goal being delayed.
                          </label>
                        </div>
                        <div class="form-check">
                        <label class="form-check-label">
                            <input type="radio" class="form-check-input" name="importance" id="optionsRadios3" value="1">
                            It is acceptable for me if this goal is not achieved by the terminal date.
                          </label>
                    </div>
            </fieldset>


            <button type="submit" class="btn btn-success btn-lg" style="float:right;">Create</button>
        </form>
    </div>
{% endblock %}

basicMVO/src/templates/portfolios/future.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Smart invest</title>
	<style>
	.form-group{
        font-family: Helvetica;

        border: none
    }

    .container{
        margin-top: 200px;
    }


	</style>
	{% include "html_dependencies.html" %}
</head>
<body style="background-color: #404040">
    <div class="container" style="background-color: #404040">
        <div class="d-flex align-items-center flex-column justify-content-center h-100 text-white" id="header">
            <h1 class="display-4">We don't know about the future yet!</h1>

            <div class="row justify-content-end" style="padding-right: 20px">
                <a href="{{ url_for('portfolios.get_portfolio_page', portfolio_id = portfolio._id) }}" class="btn btn-success" >Return to your goal summary!</a>
            </div>
        </div>
    </div>
</body>
</html>

basicMVO/src/templates/portfolios/performance.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <head>
    <style>

    #table_name {

    border-collapse: collapse;

    }

    #table_name td, #table_name th {
    border: 2px solid #ddd;
    padding: 6px;

    }



    </style>
    </head>



    <div class="mt-3">
        <h1><strong>Portfolio Details</strong></h1>
    </div>
    <hr>
    <div class="container">

        <!--<div class="row">-->
        <div class="row">


                  <div class="col-md-6">
                  <img src="data:image/png;base64, {{plot_url_list}}" width="500" height="500" alt="graph">
                  </div>




            <div class="col-md-6">


                <div class="row">
                    <p>Risk Appetite: <strong>{{ portfolio.risk_appetite }}</strong></p>
                </div>

            </div>
        </div>
        <div class= "row">

            <div class ="col">
                <a class="btn btn-primary" href="{{ url_for('portfolios.get_portfolio_page', portfolio_id = portfolio._id) }}">Return to the home page of this portfolio</a>
            </div>



        </div>
    </div>
{% endblock %}

basicMVO/src/templates/portfolios/portfolio.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <head>
    <style>

    #table_name {

    border-collapse: collapse;

    }

    #table_name td, #table_name th {
    border: 2px solid #ddd;
    padding: 6px;

    }



    </style>
    </head>



    <div class="mt-3">
        <h1><strong>Quarterly Portfolio Allocation Charts</strong></h1>
    </div>
    <hr>
    <div class="container">


        <div class="row justify-content-start">
              <div class="col">
                <div class="row">
                    <p> Tickers:
                        {% for ticker in portfolio.tickers %}
                            <a href="{{ url_for('stocks.stock_page',stock_ticker = ticker) }}">{{ ticker }}, </a>
                        {% endfor %}
                    </p>


                </div>
              </div>
        </div>




            <div class="row justify-content-start">
                  {% for i in range(plot_url_list|count) %}
                      <div class="col-6">

                        <img src="data:image/png;base64, {{plot_url_list[i]}}" width="550" height="500" style="margin:0px" alt="graph">
                      </div>
                  {% endfor %}
             </div>




        </div>
        <div class= "row" style="float:right">

            <div class ="col">
                <a class="btn btn-primary" href="{{ url_for('portfolios.get_portfolio_page', portfolio_id = portfolio._id) }}">Return to the home page of this portfolio</a>
            </div>
        </div>
    </div>
{% endblock %}

basicMVO/src/templates/portfolios/portfolio_land_page.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <head>
    <style>
        #con_1{
            margin-left: 15px;
            margin-top:10px;
            font-family: Helvetica;
            font-size: 20px;
            border: none;
        }
        #t_1{
            margin-top: 50px;
        }
        #h3{
            margin-top: 10px;
            margin-left: 0px;
        }
        #con_2{
            margin-top: 30px;

        }
        .row{
        margin-top: 10px;
        }
    </head>
    </style>
    <div class="container-fluid" id="con_2">
        <div class="row justify-content-start">
            <div class="col-7">
                <h1><strong>Portfolio Summary</strong></h1>
            </div>

            <div class="col align-self-center">
                  <a class="btn btn-primary" style="float:right;"
                 href="{{ url_for('portfolios.update_portfolio',portfolio_id = portfolio._id) }}">Edit this portfolio</a>
            </div>
            <div class="col align-self-center">
                <a class="btn btn-danger" style="float:right;" href="{{ url_for('portfolios.delete_portfolio',portfolio_id = portfolio._id) }}">Delete this portfolio</a>
            </div>
        </div>

    </div>

    <div class="container" id="con_1">
            <div class="row justify-content-start fluid">
                <h3 id="h3">Goal Description: {{portfolio.description}}
                   </h3>
            </div>
            <div class="row">
                    <h3 >Performance Plots:
                       </h3>
            </div>
            <div class="row justify-content-start">

                <div class="col-6">
                      <img src="data:image/png;base64, {{plot_url_list[0]}}" width="600" height="400" alt="graph">
                </div>
                <div class="col-5">
                      <img src="data:image/png;base64, {{plot_url_list[1]}}" width="600" height="400" alt="graph">
                </div>
            </div>

            <div class="row fluid">
                <div class="col align-self-start">
                     <table class="table" id="t_1">
                        <thead>
                            <tr>
                                <th>Start Date</th>
                                <th>Terminal Date</th>
                                <th>Initial Deposit</th>
                                <th>Target Amount</th>
                                <th>Current Balance</th>
                                <th>Goal Achieved</th>
                                <th>Quarterly Deposit</th>
                                <th>Total Years</th>
                                <th>Tickers</th>
                                <th>Years</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td><strong>{{portfolio.start_time}}</strong></th>
                                <td><strong>{{portfolio.terminal_date}}</strong></td>
                                <td>${{portfolio.initial_deposit}}</td>
                                <td>${{portfolio.amount}}</td>

                                <td>${{portfolio.account_balance[-1]|round(2)}}</td>
                                <td>{{portfolio.goal_achieved}}</td>
                                <td>${{portfolio.injection}}</td>
                                <td>{{portfolio.years}}</td>
                                <td>
                                    <p>

                                    {% for ticker in portfolio.tickers %}
                                        <a href="{{ url_for('stocks.stock_page',stock_ticker = ticker) }}">{{ ticker }}<br></a>
                                    {% endfor %}
                                    <br>
                                    </p>
                                </td>
                                <td>
                                    <p>
                                         {% for i in range(year_count) %}

                                            <a href= "{{ url_for('portfolios.get_individual_portfolio', portfolio_id = portfolio._id, year_index = i)}}"> {{year_list[i]}}<br>
                                            </a>

                                         {% endfor %}


                                     </p>
                                </td>
                            </tr>
                        <tbody>

                    </table>
                </div>
            </div>





            <div class= "row justify-content-end">

                <div class ="col-3">
                    <a class="btn btn-primary" href="{{ url_for('users.user_portfolios') }}">Return to your portfolios</a>
                </div>

            </div>


    </div>
{% endblock %}